eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: service-zuul
zuul:
  routes:
    app-feign:
      path: /api-feign/**
      serviceId: service-feign
    api-hi:
      path: /api-hi/**
      serviceId: service-hi